# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision "shell", path: "vagrant_provision.sh"
  config.ssh.insert_key = false
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 7474, host: 7474
  config.vm.network "forwarded_port", guest: 7687, host: 7687
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "private_network", ip: "192.168.50.2"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
end